apiVersion: v1
kind: Pod
metadata:
  name: ntp-pod3
spec:
  containers:
  - name: ntp-container

    image: yahyadaoudi/servers:latest
    volumeMounts:
    - name: config-volume
      mountPath: /etc/ntp.conf
      subPath: ntp.conf
    imagePullPolicy: Never
    ports:
    - containerPort: 123
volumes:
- name: config-volume
  configMap:
    name: ntp-config






